# --- Backend ---
# The GLX backend offers better performance and enables features like blur.
backend = "glx";

# --- Window transparency/opacity ---
# The active window is fully opaque, and inactive windows are slightly transparent.
inactive-opacity = 0.85;
active-opacity = 1.0;
frame-opacity = 1.0;

# Use the X Render backend for Nvidia proprietary drivers to avoid lag if using glx.
# This option can also fix flickering or tearing issues.
# vsync = true;
# use-damage = false;

# Set specific opacity rules for certain applications.
# "class_g" is the window's Xorg class. Find it with `xprop WM_CLASS`.
opacity-rule = [
  "100:class_g = 'Polybar'",
  "85:class_g = 'Alacritty'",
  "85:class_g = 'kitty'",
  "100:class_g = 'Rofi'",
  "100:class_g = 'firefox'",
  "100:class_g = 'TelegramDesktop'",
];

# --- Shadows ---
# Enabled client-side shadows on windows.
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.75;
shadow-offset-x = -15;
shadow-offset-y = -15;

# Exclude shadows from certain window types.
shadow-exclude = [
  "class_g = 'Polybar'",
  "name = 'rofi'",
  "class_g = 'Conky'",
  "class_g = 'eww'",
  "class_g = 'firefox'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# --- Fading ---
# Fade windows when opening, closing, or on opacity changes.
fading = true;
fade-delta = 10; # Time between fade steps in milliseconds.
fade-in-step = 0.05;
fade-out-step = 0.05;

# --- Rounded corners ---
# Note: Rounded corners may conflict with i3 borders. Adjust `default_border pixel` in i3 config for best results.
# See for more details on matching i3 borders with Picom rounded corners.
corner-radius = 10.0;
rounded-corners-exclude = [
    "class_g = 'Polybar'",
    "window_type = 'desktop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# --- Blur ---
# Enable background blur for transparent windows. Requires the `glx` backend.
blur-background = true;
blur-background-frame = true;
blur-method = "gaussian";
blur-strength = 10;

# Exclude blur from certain window types and applications.
blur-background-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'firefox'",
  "class_g = 'Conky'",
  "class_g = 'eww'",
  "window_type = 'desktop'",
  "name = 'rofi'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];
