# fish aliases
alias clock="clock-rs -c '#8bb2c9' --blink --bold --fmt '%m/%d/%Y'"
alias lo "eza -lha"
alias lzs "lazysql"
alias lzd "lazydocker"
alias lzg "lazygit"
alias ipa "ifdata -pa wlp3s0"
alias csp "codesnap"
alias ff "fastfetch"
alias rtx "curl rate.sx?n=10"
alias cht "curl cht.sh"
alias trp "trip -p tcp 8.8.4.4"
alias pbpaste "xclip -selection clipboard -o"
alias hst "history"
alias cmx "cmatrix -bas -u 10 -C green"
alias srvcs "systemctl list-units --type=service --state=running"
alias wtr "curl wttr.in?32808"
alias sdm "systemd-manager-tui"
alias dlph "dolphie"
alias pst "posting"
alias mmr "memray"
