# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#
#
background_opacity 0.50
font_family SF Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16
shell /usr/bin/bash
term xterm-256color

# Set window padding
window_padding_width 5
window_padding_height 5

# Set margin between split windows
window_margin_width 5
window_margin_height 5

# not confirm on exit
confirm_os_window_close 0

# cursor
cursor_shape block
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0

